expozurecardwebsite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/urls.py
from .views import *
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('Login/', LoginPage, name="LoginPage"),
    path('Register/', RegisterUser, name="RegisterPage"),
    path('Logout/', logoutuser, name="Logout"),
    path('', home, name="Home"),
    path('EditProfile/', EditProfile, name="EditProfile"),
    path('Profile/', Profile, name="Profile"),
    path('ShareProfile', shareprofile, name="ShareProfile"),
    path('delete_link/<int:pk>', delete_link, name="delete_link"),
    path('update_link/<int:pk>', update_link, name="update_link"),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from tkinter import CASCADE
from turtle import color
from django.db import models
from django.forms import SlugField
from django.contrib.auth.models import User
from django.forms import SlugField
from .helpers import *
# Create your models here.


class themecolor(models.Model):
    ThemeColor = models.CharField(max_length=300)


class Profil(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Name = models.CharField(max_length=300, null=True, blank=True)
    profession = models.CharField(max_length=300, null=True, blank=True)
    emiall = models.EmailField(null=True, blank=True)
    number = models.IntegerField(null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    slug = models.SlugField(max_length=1000, null=True, blank=True)
    color = models.CharField(max_length=300, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return str(self.user)

    def save(self, *args, **kwargs):
        self.slug = generate_slug(self.user.username)
        super(Profil, self).save(*args, **kwargs)

    def get_full_name(self):
        if not self.Name:
            return 'Your Name'
        return ' '.join([self.Name])

    def get_full_Profesion(self):
        if not self.profession:
            return 'Your Profesion'
        return ' '.join([self.profession])

    def datasae(self, n, p, e, no, img):
        self.Name = n
        self.profession = p
        self.emiall = e
        self.number = no
        if img:
            self.image = img


class Links(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    link = models.CharField(max_length=300)

home/views.py
from asyncio.windows_events import NULL
from multiprocessing import context
import os
from tokenize import Name
from unicodedata import name
from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm

from .models import Profil, Links
from .Forms import CreateUserForm, CreateProfileForm, ChangeUserForm, UpdateLinksForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from . import Forms
# Create your views here.


def LoginPage(request):
    Page = 'login'
    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('Home')
        else:
            messages.error(request, 'User Name and Password is Incorrect')

    context = {'Page': Page}
    return render(request, 'index.html', context)


def logoutuser(request):
    logout(request)
    return redirect('LoginPage')


def RegisterUser(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            fullname = None
            profesion = None
            EMail = None
            Number = None
            image = None
            user1 = user
            # print(fullname,profesion,EMail,Number,image,user1)
            ins = Profil(user=request.user, Name=fullname,
                         profession=profesion, emiall=EMail, number=Number, image=image)
            ins.save()
            print(ins)
            return redirect('Home')
        else:
            messages.error(request, 'Kindly Fill form Properly')

    context = {'form': form}
    return render(request, 'index.html', context)


@login_required(login_url='LoginPage')
def home(request):
    context = {}
    profile_obj = request.user.profil
    context['profile_obj'] = profile_obj
    if request.method == "POST":
        Instagram = request.POST.get('Instagram')
        if Instagram:
            link = Links(user=request.user, name='Instagram', link=Instagram)
            link.save()

        Facebook = request.POST.get('Facebook')
        if Facebook:
            link = Links(user=request.user, name='Facebook', link=Facebook)
            link.save()

        Twitter = request.POST.get('Twitter')
        if Twitter:
            link = Links(user=request.user, name='Twitter', link=Twitter)
            link.save()

        Youtube = request.POST.get('Youtube')
        if Youtube:
            link = Links(user=request.user, name='Youtube', link=Youtube)
            link.save()

        Other_Links = request.POST.get('Other_Links')
        if Other_Links:
            link = Links(user=request.user,
                         name='Other_Links', link=Other_Links)
            link.save()

    return render(request, 'Home.html', context)


@login_required(login_url='LoginPage')
def EditProfile(request):
    form1 = CreateProfileForm(
        request.POST or None, request.FILES or None, instance=request.user.profil)
    form2 = ChangeUserForm(request.POST or None, instance=request.user)
    if form1.is_valid() and form2.is_valid():
        form1.save()
        form2.save()

    context = {'form1': form1, 'form2': form2}
    return render(request, 'editprofile.html', context)

@login_required(login_url='LoginPage')
def Profile(request):
    return render(request, 'Profile.html')

def delete_link(request, pk):
    link = Links.objects.get(pk=pk)
    link.delete()
    messages.error(request, f'{link.name} link deleted')
    return redirect('Profile')



def update_link(request,pk):
    link = Links.objects.get(pk=pk)
    form = UpdateLinksForm(request.POST or None, instance=link)
    if form.is_valid():
        form.save()
        return redirect('Profile')
    context = {'form':form, 'link':link}
    return render(request, 'model_data.html', context)


def shareprofile(request):
    return render(request, 'shareprofile.html')

templates/Home.html
{% extends 'base.html' %} {% load static %} {% block Content %}

<div class="container">
  {% if not profile_obj.image %}
  <div class="imagecontainer">
    <img class="round" src="{%static '/images/Tony.jpg'%}" alt="" />
  </div>
  {% else %}
  <div class="imagecontainer">
    <img class="round" src="{{profile_obj.image.url}}" alt="" />
  </div>
  {% endif %}
  <div class="textcontainer">
   
    
    <h1>{{profile_obj.get_full_name}}</h1>

    <h2>{{profile_obj.get_full_Profesion}}</h2>
   
  </div>
  <form method="post" id="pro_form">
    {% csrf_token %}
  </form>
  <div class="ind">
    <input
      class="in border-gradient"
      type="text"
      name="Instagram"
      form="pro_form"
      placeholder="Instagram"
      style="background-image: url({%static '/images/insta.png'%})"
    />
  </div>
  <div class="ind">
    <input
      class="fb border-gradient2"
      type="text"
      form="pro_form"

      name="Facebook"
      placeholder="Facebook"
      style="background-image: url({%static '/images/FB.png'%})"
    />
  </div>
  <div class="ind">
    <input
      class="tw border-gradient3"
      type="text"
      form="pro_form"

      name="Twitter"
      placeholder="Twitter"
      style="background-image: url({%static '/images/twitter.png'%})"
    />
  </div>
  <!-- <div class="ind"><input class="tt border-gradient4" type="text" placeholder="Tiktok" >
    </div> -->
  <div class="ind">
    <input
      class="yt border-gradient5"
      type="text"
      form="pro_form"

      name="Youtube"
      placeholder="Youtube"
      style="background-image: url({%static '/images/YouTube.png'%})"
    />
  </div>
  <div class="ind">
    <input
      class="ww border-gradient6"
      type="text"
      form="pro_form"

      name="Other_Links"
      placeholder="Other Links"
      style="background-image: url({%static '/images/www.png'%})"
    />
  </div>
  <button
    type="submit"
    form="pro_form"

    class="btn btn-lg"
    style="margin-right: 1rem; background-color: #ff4b2b; color: #fff"
  >
    Save
  </button>
</div>
{% endblock %}

templates/Profile.html
{% extends 'base.html' %} {% load static %} {% block Content %}

<div class="container">
  
  {% if not request.user.profil.image %}
  <div class="imagecontainer">
    <img class="round" src="{%static '/images/Tony.jpg'%}" alt="" />
  </div>
  {% else %}
  <div class="imagecontainer">
    <img class="round" src="{{request.user.profil.image.url}}" alt="" />
  </div>
  {% endif %}
  <div class="textcontainer">
    <h1>{{request.user.profil.Name}}</h1>
    <h2>Profession</h2>
    <div class="smailllinks">
      <a href="http://"
        ><i
          class="icon fa-regular fa-envelope"
          style="color: #fff; font-size: 2.5rem; margin: 0.5rem 2rem 1rem 0rem"
        ></i
      ></a>
      <a href="http://">
        <i
          class="icon fa-solid fa-phone"
          style="color: #fff; font-size: 2.5rem; margin: 0.5rem 1rem 1rem 0rem"
        ></i
      ></a>
    </div>
  </div>
  <div class="linkbutton">
    {% for button in request.user.links_set.all %}
    
    {% if button.name == "Youtube" %}

    <a
      class="yt ghost2"      
      style="color: black;"
      href="{% url 'update_link' button.id %}"

    >
      {{button.name}}
    </a>
      {% else %}

    <a
    role="button"
    class="in ghost2 update_link"
    id="{{button.id}}"
    href="{% url 'update_link' button.id %}"
    style="color: black;"
  >
    {{button.name}}
  </a>
    {% endif %}
      
    {% endfor %}

    
  </div>
  <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    role="dialog"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
            Update or Delet Link
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="bodyfooter">
          
        </div>
      </div>

      </div>
    </div>
  </div>

  <!-- ===========================================YOUTUBE START -->
  <div
    class="modal fade"
    id="YOUTUBEMODEL"
    tabindex="-1"
    role="dialog"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
            Update or Delet Link
          </h5>
          <button
            type="button"
            class="close"
            data-dismiss="modal"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="recipient-name" class="col-form-label">Link:</label>
              <input type="text" class="form-control" id="recipient-name" />
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-dismiss="modal"
            style="margin-right: 1rem; background-color: #ff4b2b; color: #fff"
          >
            Update
          </button>
          <button
            data-dismiss="modal"
            type="button"
            class="btn btn-dangrous"
            style="margin-right: 1rem; background-color: #bea631; color: #fff"
            onclick="videoopen()"
          >
            VIEW
          </button>
          <button
            data-dismiss="modal"
            type="button"
            class="btn btn-dangrous"
            style="margin-right: 1rem; background-color: #ff2b4b; color: #fff"
          >
            Delet
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- ===========================================YOUTUBE END  -->
</div>
<div class="popup_video">
  <span onclick="videoclose()">&times;</span>
  <video
    src="https://www.youtube.com/watch?v=wXG11HcJtOw"
    autoplay
    controls
  ></video>
</div>

<script>

  function initThemeSelector() {
    const themeSelect = document.getElementById("themeSelect");
    const themeStylesheetLink = document.getElementById("stylesheetlink");
    const currentTheme = localStorage.getItem("theme") || "default";

    function activateTheme(themeName) {
      themeStylesheetLink.setAttribute("href", `css/themes/${themeName}.css`);
    }

    themeSelect.addEventListener("change", () => {
      activateTheme(themeSelect.value);
      localStorage.setItem("theme", themeSelect.value);
    });

    themeSelect.value = currentTheme;
    activateTheme(currentTheme);
  }

  initThemeSelector();

  function videoopen() {
    document.querySelector(".popup_video").style.display = "block";
  }
  function videoclose() {
    document.querySelector(".popup_video").style.display = "none";
  }
</script>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <!-- custom css link -->
    <link rel="stylesheet" href="{%static '/css/home.css'%}" />
    <title>Expozure</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'Home' %}"
        ><img
          src="{%static '/images/Main logo slogan_edited 1.png'%}"
          alt=""
          srcset=""
      /></a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Home' %}"
              >Home <span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'EditProfile'%}">Edit Profile </a>
          </li>

          <li class="nav-item active">
            <a class="nav-link disabled" href="{% url 'Profile'%} ">Profile</a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <button
            class="btn my-2 my-sm-0"
            type="submit"
            style="margin-right: 1rem; background-color: #ff4b2b; color: #fff"
          >
            Copy Profile Link
          </button>
          <a
            class="btn my-2 my-sm-0"
            type="submit"
            href="{% url 'Logout' %}"
            style="margin-right: 1rem; background-color: #b97b11; color: #fff"
          >
            Log out
          </a>
        </form>
      </div>
    </nav>
    {% block Content %} {% endblock %}
    <footer class="ftr">
      <div class="topcontainer">
        <p>Via</p>
        <img
          src="{%static '/images/Main logo slogan_edited 1.png'%}"
          alt=""
          srcset=""
        />
      </div>
      <a href="#">Buy Expozure Card</a>
    </footer>
  </body>
</html>

templates/editprofile.html
{% extends 'base.html' %} {% load static %} {% block Content %}
{% if messages %}
<ul class="messages">
  {% for message in messages %}

  <div
    class="alert alert-danger alert-dismissible fade show"
    role="alert"
    style="z-index: 5000000000000000"
  >
    {{ message }}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
  </div>
  {% endfor %}
</ul>
{% endif %}
<div class="color_switcher">
  <div class="switcherbutton" onclick="active()">
    <!-- <i class="fas fa-cog"></i> -->
    <i class="fa-solid fa-palette"></i>
  </div>
  <h3>Select Color</h3>
  <div class="theme_button_container">
    <span
      class="theme_button"
      data-color="#fff"
      style="background: rgb(69, 65, 65)"
      onclick="changecolor('rgb(69, 65, 65)')"
    >
    </span>
    <span
      class="theme_button"
      data-color="#fff"
      style="background: rgb(203, 30, 30)"
      onclick="changecolor('rgb(203, 30, 30)')"
    >
    </span>
    <span
      class="theme_button"
      data-color="#fff"
      style="background: rgb(20, 245, 54)"
      onclick="changecolor('rgb(20, 245, 54)')"
    >
    </span>
    <span
      class="theme_button"
      data-color="#fff"
      style="background: rgb(20, 245, 54)"
      onclick="changecolor('rgb(20, 245, 54)')"
    >
    </span>
    <span
      class="theme_button"
      data-color="#fff"
      style="background: rgb(20, 245, 54)"
      onclick="changecolor('rgb(20, 245, 54)')"
    >
    </span>
    <span
      class="theme_button"
      data-color="#fff"
      style="background: rgb(40, 7, 49)"
      onclick="changecolor('#fff')"
    >
    </span>
  </div>
</div>

<div class="container">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form2}}
    {{form1}}
    <button
      type="submit"
      class="btn btn-lg"
      style="margin-right: 1rem; background-color: #ff4b2b; color: #fff"
    >
      Save
    </button>
  </form>
</div>

<script>
  function active() {
    document.querySelector(".color_switcher").classList.toggle("active");
  }
  let themebutton = document.querySelectorAll("theme_button");
  console.log(themebutton);
  function changecolor(color) {
    document.querySelector(":root").style.setProperty("--main-color", color);
    // localStorage.setItem("theme", color);
  }
  themebutton.forEach((color) => {
    color.addEventListener("Click", () => {
      let dataColor = color.getAttribute("data-color");
      console.log(dataColor);
      document
        .querySelector(":root")
        .style.setProperty("--main-color", dataColor);
    });
  });
  function initThemeSelector() {
    const themeSelect = document.getElementById("themeSelect");
    const themeStylesheetLink = document.getElementById("stylesheetlink");
    const currentTheme = localStorage.getItem("theme") || "default";

    function activateTheme(themeName) {
      themeStylesheetLink.setAttribute("href", `css/themes/${themeName}.css`);
    }

    themeSelect.addEventListener("change", () => {
      activateTheme(themeSelect.value);
      localStorage.setItem("theme", themeSelect.value);
    });

    themeSelect.value = currentTheme;
    activateTheme(currentTheme);
  }

  initThemeSelector();
</script>
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- bootstrap css cdn -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <!-- bootstrap js cdn -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <!-- font  -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@400;500;700&display=swap"
      rel="stylesheet"
    />
    <!-- custom css -->
    <link
      rel="stylesheet"
      id="stylesheetlink"
      href="{%static '/css/themes/default.css'%}"
    />
    <!-- <link rel="stylesheet" href="./css/themes/primary.css" /> -->
    <link rel="stylesheet" href="{% static '/css/style.css'%}" />
    <title>EXPOZURE</title>

    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/gh/kenwheeler/slick@1.8.1/slick/slick-theme.css"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"
    />
    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"
    ></script>
    <!-- slick links -->
  </head>

  <body>
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}

      <div
        class="alert alert-danger alert-dismissible fade show"
        role="alert"
        style="z-index: 5000000000000000"
      >
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
      </div>
      {% endfor %}
    </ul>
    {% endif %}


  {% if Page == 'login' %}
    <div class="form-container sign-in-container hide">
      <form method="POST" action="">
        {% csrf_token %}
        <h1>Welcome To</h1>
        <img src="{%static '/images/Main logo slogan_edited 1.png'%}" alt="" />
        <input type="text" placeholder="User Name" name="username" />
        <input type="password" placeholder="Password" name="password" />
        <button type="submit">Sign In</button>
        <a href="{% url 'RegisterPage' %}" class="createaccount" onclick="change()">Create Account</a>
      </form>
    </div>
  {% else %}
    <div class="form-container sign-in-container hide ">
      <form method="Post" action="#">
        <h1>Create Account</h1>
        {% csrf_token %}
        {{form}}
        {% comment %} {{form.username}}  {% endcomment %}
        {% comment %}
        <input type="text" placeholder="Name" /> {% endcomment %} {% comment %}
        <input type="email" placeholder="Email" /> {% endcomment %}
        {% comment %} {{form.email}} {% endcomment %}
         {% comment %}
        <input type="password" placeholder="Password" /> {% endcomment %}
        {% comment %} {{form.password}} {% endcomment %}
        <button type="submit">Sign Up</button>
        <a href="{% url 'LoginPage' %}" class="createaccount" onclick="rechange()">Login</a>
      </form>
    </div>
  {% endif %}
  {% if Page != 'login' %}
    <div class="container right-panel-active" id="container">
      
      <div class="form-container  sign-up-container">
        <form method="Post" action="#">
          <h1>Create Account</h1>
          {% csrf_token %}
          {{form}}
          {% comment %} <input type="text" placeholder="Name" />
          <input type="email" placeholder="Email" />
          <input type="password" placeholder="Password" /> {% endcomment %}
          <button type="submit">Sign Up</button>
        </form>
      </div>
      {% else %}
      <div class="container" id="container">
      <div class="form-container sign-in-container">
        <form method="POST" action="">
          {% csrf_token %}
        <h1>Welcome To</h1>
        <img src="{% static '/images/Main logo slogan_edited 1.png'%}" alt="" />
        <input type="text" placeholder="User Name" name="username" />
        <input type="password" placeholder="Password" name="password" />
        <button type="submit">Sign In</button>
        </form>
      </div>
      {% endif %}
      <div class="overlay-container">
        <div class="overlay">
          <div class="overlay-panel overlay-left">
            <h1>Welcome Back!</h1>
            <p>
              To keep connected with us please login<br />
              with your personal info
            </p>
           <a href="{% url 'LoginPage' %}"> <button class="ghost" id="signIn" style="">Sign In</button></a>
          </div>
          <div class="overlay-panel overlay-right">
            <h1>
              New Thinking <br />
              New Expozure
            </h1>
            <p>Your Buisiness Needs Expozure</p>
            <a href="{% url 'RegisterPage' %}"> <button class="ghost" id="signUp">Sign Up</button></a>
          </div>
        </div>
      </div>
    </div>
    <script>
      function change() {
        document.querySelector(".clickhide").className =
          "form-container sign-in-container hide clickshow";
        console.log("clicked");
      }
      function rechange() {
        document.querySelector(".clickshow").className =
          "form-container sign-in-container hide clickhide";
      }
    </script>

    <script src="{%static '/js/app.js'%}"></script>
  </body>
</html>